---
name: Acceptenace Test
on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    paths:
    - '.github/workflows/acceptance-test.yaml'
    - 'examples/**'
    - 'test/**'
    - '*.tf'
  pull_request:
    branches:
    - master
    paths:
    - '.github/workflows/acceptance-test.yaml'
    - 'examples/**'
    - 'test/**'
    - '*.tf'
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::068189904525:role/github-openid-connect
        role-session-name: github-actions-terraform-aws-marbot-monitoring-basic
        aws-region: us-east-1
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.6'
        cache-dependency-path: test/go.sum
    - working-directory: test
      env:
        MARBOT_ENDPOINT_ID: ${{ secrets.MARBOT_ENDPOINT_ID }}
      run: go test
